canPlay: true
labyrinthSize: 21

Material: "SPRUCE_SAPLING"
Leftspinarrowcmd: 600
Logiconcmd: 601
Rightspinarrowcmd: 602
Selectandattackiconcmd: 603
Settungiconcmd: 604
Soundiconcmd: 605
Trophyiconcmd: 607
Playerstatusiconcmd: 606
Uparrowcmd: 608
itembagiconcmd: 609
Rankingiconcmd: 700
#WEW
#WEW
#WEW
View1:
#WWW
#WEE
#WEW
View2:
#WWW
#EEW
#WEW
View3:


